// <auto-generated />
namespace ProjectLikeStackOverflow1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class nameFieldModified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nameFieldModified));
        
        string IMigrationMetadata.Id
        {
            get { return "201608111850257_nameFieldModified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
